spring:
 application:
  name: file-integration-service

server:
 port: 8500
 servlet:
  contextPath: /fileIntegration

ftp:
 host: 192.168.0.2
 username: ftp-user
 password: ftp-user
 port: 21
 directory:

security:
 enable-csrf: true

file:
 downloadPath: /tmp